### ISSUE TITLE
UI: Layout: Create sublayout: debug mode.

### ISSUE THREAD

**Issue by estory1** [DePaul-Medix/SmartCAD#4]

**Comment by lqdev** [comment]
https://docs.google.com/drawings/d/1voTgIqkX6In0y54Znilu0J5GdMYm1TFZ9gsStEY1XX0/edit

See link (debug mode query section under search bar)

**Comment by lqdev** [comment]
Debug mode has been completed. Debug mode allows admin to view the time at which errors occurred as well as the text representation and SQL query performed. Additional information such as the server response (i.e. 400,500) as well as method of input when performing search by the user are available. Datatables Jquery plugin used to provide search, sort, pagination, and filtering capabilities to debug/error log.
